from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "questions" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "text" VARCHAR(30) NOT NULL,
    "category" VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS "quotes" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "content" TEXT NOT NULL,
    "author" VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "nickname" VARCHAR(20) NOT NULL UNIQUE,
    "hashed_password" VARCHAR(128) NOT NULL,
    "is_active" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "bookmarks" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "bookmarks_has_quotes" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "bookmark_id" INT NOT NULL REFERENCES "bookmarks" ("id") ON DELETE CASCADE,
    "quote_id" INT NOT NULL REFERENCES "quotes" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "diaries" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "title" VARCHAR(50) NOT NULL,
    "text" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "token_blacklist" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "token" VARCHAR(255) NOT NULL,
    "expired_at" TIMESTAMPTZ,
    "user_id" INT REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztW21z2jgQ/isMn9KZXCeQ0GbuGxBy5RrCNaEv05sbj7AVo8GWiC03YXr895OEX2T55e"
    "wAjZ34S4esdm3to5X22ZX7s20TA1ru2wEhSxs4y/bvrZ9tDGzIfiTGjlttsFpFI1xAwdwS"
    "ynNfS0jB3KUO0CkbuAOWC5nIgK7uoBVFBDMp9iyLC4nOFBE2I5GH0b0HNUpMSBfQYQN//8"
    "PECBvwEbrBn6uldoegZcTmiwz+biHX6HolZGNML4Uif9tc04nl2ThSXq3pguBQG2HKpSbE"
    "0AEU8sdTx+PT57PzXQ082s40UtlOUbIx4B3wLCq5WxADnWCOH5uNKxw0+Vt+63bO3p+dn7"
    "47O2cqYiah5P1m617k+9ZQIHA9a2/EOKBgqyFgjHDTHcid1QBN4nfBRiiyYTqIcUsFTMM3"
    "fRv8UKENgMzDNhBE4EYBtSd0mQ/GFFtrf+FyoJyNJ6PbWX/yF/fEdt17S0DUn434SFdI14"
    "r06N0bLidsO2w3SviQ1tfx7EOL/9n6Pr0eCQSJS01HvDHSm31v8zkBjxINkwcNGFKMBdIA"
    "GKYZLaznQkcrtSski//fGhVZvz3sDn6k3C1TNwdHJAngJXEgMvFHuBY4jtmMANZhCm7+If"
    "rZf0z18NsEMRBIo+BywEN4zMqhwdxjTkEqHBz2b4f9i1FbgDgH+vIBOIaWgWaQJbR7j1Do"
    "JoEd+A+4/HgDLSB8ycQ0SEyf+LPqBa4Ai3SJBFIMvuSQ3bVTEc0CcgLwekb4vwUj9MkoHj"
    "r95QSomLqm8JXQEYdHEMtOavBt0SKOQHoJ1yGMfniHq+CPhXb+OF04xDMX8aEFcKWgTt0h"
    "TK4lwBWRYAMMTCHjEGyOM0I8h5yFThdgaMpcG7JWtXSUR9bCE7QUgIrVa8rtMiGSd3lB5G"
    "ST1wRbDiWaSwXhjrRIri2rh2NRaqTsrnR6lIjDPcBXQ+ajYifvr7K8ckcSlZt5LxBw1mkZ"
    "dzuQm2kNpoKa5Fq/5EoRtVL25XABnHTsQgMFPjbpam5LFvCPmgWxSTl/7Z3kwPWlfzP80L"
    "856p0oHYxrf6QrhuIZlsLHlC7SjEkzAPT164JfXndo9G0WawwFOB1N+t/exJpDV9PrPwJ1"
    "Cdfh1XSg4Nn05l5qb25lPHFh45bNwj7rwvqTb3quTc+1Wj3XQ3LjTx50fZcT9Dgcy2XI97"
    "5Ww5Hrx5FTGV4ORa4Zw4sz5NMiDPk0myGfJhiyzrw1ybaELIqhbFNPHDu9Ajh2epk48qGU"
    "nPFc519GN75AF77pu9fz2GOvoxCXqm0lk7ps2l9d3jImvSApXC/7KIws6oJp/CDs9oqchE"
    "wr8ygUY6XOQvUCJH4R2ty/73L/noNl6Sv4XW5DqnYLL/uiXsRL3yzEb+HVm3b1Jl6+LNjX"
    "LXwYDpnpfkaWEA8sNhcLuTQt7ysauQSAcl1tHlNumECNmIBYwFIVUGDwyjOWnPjh4wo5T2"
    "p/xi330P70w68iLKtC3c7A7Yp9Y/rr1+tFtTufLdzr2u0UuKYk/QDv7FTPHWpK/doleGgD"
    "ZJVJ8KHBfhL8wfE7fHrHSF+K3yVQlG1qCWSRVnE3u1XcTbSKWTWzYExnBVz3gTgpuzkbzB"
    "TTerLPTve8SOe4e57dOuZjcWCRq7HTGP1IiU9Wt1oQ4IxDUrZT8GRFqHUoQMO43TfdHEyn"
    "VzGmORirXbvPk8GIASzgZUpom5OT39Y2X6q8iA8aov+UULq5uOe2YjUXOrOjKO8F6QPQp+"
    "MQfmhaUxBE22NHDJKNtdpUN7u2mHNrkj50kL5op1Ql/shxXl0CIp2mMNlnEjhwYfKDlZP+"
    "dinKAyWTevK/g5QnfGuUANFXryeAnZMidQnTyibQJ8mPWLJuw/+8nV6XvQ03kE5b/7YKnv"
    "DVuhXn/ubfiqsX4ApB4w8YPPenLZv/AOGI9po="
)
